apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radius-demo-webapp
  description: An example of a Backstage application.
  annotations:
    backstage.io/kubernetes-id: radius-demo-webapp
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: guests
  lifecycle: experimental
  system: examples
  dependsOn:
    - "resource:reddis"