apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: {{ .Release.Namespace }}
  labels:
    backstage.io/kubernetes-id: radius-demo-webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000